### ISSUE TITLE
ti edit throws error after closing

### ISSUE THREAD

**Issue by mohanisch** [dribnif/ti#5]
`/usr/local/lib/python3.7/site-packages/ti-0.9.0-py3.7.egg/ti/actions/write/edit.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
`

**Comment by dribnif** [comment]
Thanks, I'm on it.

**Comment by dribnif** [comment]
fixed in https://github.com/dribnif/tt
